# Generated by Django 5.2.9 on 2026-06-05 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.department'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.district'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tramite.document'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='from_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p_outgoing_flows', to='tramite.area'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='to_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_incoming_flows', to='tramite.area'),
        ),
        migrations.AddField(
            model_name='procedurefile',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tramite.procedure'),
        ),
        migrations.AddField(
            model_name='procedurefile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='from_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_flows', to='tramite.area'),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='tramite.procedure'),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='to_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_flows', to='tramite.area'),
        ),
        migrations.AlterUniqueTogether(
            name='proceduresequence',
            unique_together={('tramite_type', 'year')},
        ),
        migrations.AddField(
            model_name='province',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.department'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.province'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.province'),
        ),
        migrations.AddField(
            model_name='userarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_users', to='tramite.area'),
        ),
        migrations.AddField(
            model_name='userarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='procedureflow',
            index=models.Index(fields=['procedure', 'sequence'], name='tramite_pro_procedu_8c6f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureflow',
            index=models.Index(fields=['to_area', 'status'], name='tramite_pro_to_area_28a756_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('code', 'agency'), name='unique_code_per_agency'),
        ),
        migrations.AlterUniqueTogether(
            name='userarea',
            unique_together={('user', 'area')},
        ),
    ]
