# Generated by Django 5.2.9 on 2026-06-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='tramite_type',
            field=models.CharField(choices=[('TE', 'Tramite externo'), ('TI', 'Tramite interno'), ('TV', 'Tramite virtual')], db_index=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
