# Generated by Django 5.2.9 on 2026-06-05 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_procedure_tramite_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='procedure',
            name='unique_code_per_agency',
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('code', 'tramite_type'), name='unique_code_per_type'),
        ),
    ]
