# Generated by Django 5.2.9 on 2026-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_remove_procedure_unique_code_per_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='numeracion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
