# Generated by Django 5.2.9 on 2026-06-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_procedure_numeracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureflow',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tramite.document'),
        ),
        migrations.AddField(
            model_name='procedureflow',
            name='folios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
